version: '3.7'

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasalexa/data/db
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasalexa/data/wordpress

services:
  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args: 
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_USER
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
        - MYSQL_DATABASE  
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:
